#!/bin/sh
logger -i -t "tinc.tap-l6" "subnet-down, iface=$INTERFACE, node=$NODE, remoteaddress=$REMOTEADDRESS, remoteport=$REMOTEPORT, subnet=$SUBNET, weight=$WEIGHT"
DIR=$(dirname -- "$(readlink -f -- "$0";)")
if [ "$REMOTEADDRESS" ]; then
    IP=${SUBNET%/*}
    MASK=${SUBNET#*/}
    ROUTEDIR="$DIR/routes/ip=$IP,mask=$MASK"
    [ -f "$ROUTEDIR/$REMOTEADDRESS" ] && rm "$ROUTEDIR/$REMOTEADDRESS"
    [ "0" = "$(ls $ROUTEDIR | wc -l | tr -d ' ')" ] && rm -rdf $ROUTEDIR 
fi
/bin/sh $DIR/routes.sh
