#!/bin/sh
logger -i -t "tinc.tap-l6" "tinc-up, name=$NAME, iface=$INTERFACE"
ifconfig $INTERFACE 10.254.1.1 netmask 255.255.0.0
ifconfig $INTERFACE up
if ifconfig tap-l6 2>/dev/null; then
    RAND=$(od -A n -t d -N 1 /dev/random)
    ifconfig tap-l6 name tap-l6-$RAND
    ifconfig tap-l6-$RAND down
    for ITEM in $(netstat -rn | grep tap-l6-$RAND | cut -d' ' -f1); do
        route delete $ITEM -interface tap-l6-$RAND
    done
    ifconfig tap-l6-$RAND destroy &
fi
ifconfig $INTERFACE name tap-l6
#route add -net 224.0.0.0/4 -interface tap-l6 || echo 'multicast route already exists'
DIR=$(dirname -- "$(readlink -f -- "$0";)")
[ -d "$DIR/routes" ] && rm -rdf "$DIR/routes"
